### ISSUE TITLE
Fails to build with Vulkan-Headers v1.3.213

### ISSUE THREAD

**Issue by jbeich** [vkmark/vkmark#40]
Regressed by https://github.com/KhronosGroup/Vulkan-Headers/commit/33d4dd987fc8

```c++
$ meson setup _build
$ meson compile -C _build
[...]
../src/vkutil/pipeline_builder.cpp:204:12: error: no matching constructor for initialization of 'ManagedResource<vk::Pipeline>'
    return ManagedResource<vk::Pipeline>{
           ^                            ~
../src/managed_resource.h:34:5: note: candidate constructor not viable: no known conversion from 'ResultValue<vk::Pipeline>' to 'vk::Pipeline' for 1st argument
    ManagedResource(T&& raw, Destructor&& destructor)
    ^
../src/managed_resource.h:40:5: note: candidate constructor not viable: requires single argument 'rhs', but 2 arguments were provided
    ManagedResource(ManagedResource&& rhs)
    ^
../src/managed_resource.h:28:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct ManagedResource
       ^
../src/managed_resource.h:32:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    ManagedResource() = default;
    ^
```

**Comment by SupervisedThinking** [comment]
same here:
```
FAILED: src/vkmark.p/vkutil_pipeline_builder.cpp.o 
/mnt/dev/LibreELEC-RR/build.LibreELEC-wayland.x86_64-11.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ -Isrc/vkmark.p -Isrc -I../src -I/mnt/dev/LibreELEC-RR/build.LibreELEC-wayland.x86_64-11.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O0 '-DVKMARK_WINDOW_SYSTEM_DIR="/usr/lib/vkmark"' '-DVKMARK_DATA_DIR="/usr/share/vkmark"' '-DVKMARK_VERSION_STR="2017.08"' -march=x86-64 -Wall -pipe -O3 -fomit-frame-pointer -DNDEBUG -MD -MQ src/vkmark.p/vkutil_pipeline_builder.cpp.o -MF src/vkmark.p/vkutil_pipeline_builder.cpp.o.d -o src/vkmark.p/vkutil_pipeline_builder.cpp.o -c ../src/vkutil/pipeline_builder.cpp
../src/vkutil/pipeline_builder.cpp: In member function 'ManagedResource<vk::Pipeline> vkutil::PipelineBuilder::build()':
../src/vkutil/pipeline_builder.cpp:206:78: error: no matching function for call to 'ManagedResource<vk::Pipeline>::ManagedResource(<brace-enclosed initializer list>)'
  206 |         [vptr=&vulkan] (auto const& p) { vptr->device().destroyPipeline(p); }};
      |                                                                              ^
In file included from ../src/vkutil/pipeline_builder.h:27,
                 from ../src/vkutil/pipeline_builder.cpp:23:
../src/managed_resource.h:40:5: note: candidate: 'ManagedResource<T>::ManagedResource(ManagedResource<T>&&) [with T = vk::Pipeline]'
   40 |     ManagedResource(ManagedResource&& rhs)
      |     ^~~~~~~~~~~~~~~
../src/managed_resource.h:40:5: note:   candidate expects 1 argument, 2 provided
../src/managed_resource.h:34:5: note: candidate: 'ManagedResource<T>::ManagedResource(T&&, ManagedResource<T>::Destructor&&) [with T = vk::Pipeline; ManagedResource<T>::Destructor = std::function<void(vk::Pipeline&)>]'
   34 |     ManagedResource(T&& raw, Destructor&& destructor)
      |     ^~~~~~~~~~~~~~~
../src/managed_resource.h:34:25: note:   no known conversion for argument 1 from 'vk::ResultValue<vk::Pipeline>' to 'vk::Pipeline&&'
   34 |     ManagedResource(T&& raw, Destructor&& destructor)
      |                     ~~~~^~~
../src/managed_resource.h:32:5: note: candidate: 'constexpr ManagedResource<T>::ManagedResource() [with T = vk::Pipeline]'
   32 |     ManagedResource() = default;
      |     ^~~~~~~~~~~~~~~
../src/managed_resource.h:32:5: note:   candidate expects 0 arguments, 2 provided
ninja: build stopped: subcommand failed.
```
